# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaACompetir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(choices=[('ELITE', 'Elite'), ('INFANTILES', 'Infantiles'), ('JUVENILES', 'Juveniles'), ('ADULTOS', 'Adultos')], max_length=15)),
                ('distancia', models.CharField(choices=[('MED', 'Media'), ('ALL', 'Entera')], max_length=15)),
                ('edad', models.CharField(max_length=8)),
                ('precio', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Categor\xeda a Competir',
                'verbose_name_plural': 'Categor\xedas a Competir',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagado', models.BooleanField(default=False, help_text='Marcar si se realiz\xf3 la transferencia')),
                ('rut', models.CharField(help_text='12345678-5', max_length=11, verbose_name='RUT')),
                ('nombre', models.CharField(help_text='Alvaro', max_length=16, verbose_name='Nombre')),
                ('apellido_pat', models.CharField(help_text='Alvarado', max_length=16, verbose_name='Apellido Paterno')),
                ('apellido_mat', models.CharField(help_text='Aguirre', max_length=16, verbose_name='Apellido Materno')),
                ('sexo', models.CharField(choices=[('HOMBRE', 'Hombre'), ('MUJER', 'Mujer')], default='HOMBRE', max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('telefono', models.CharField(max_length=16, verbose_name='Tel\xe9fono')),
                ('celular', models.CharField(max_length=16, verbose_name='Celular')),
                ('comuna', models.CharField(blank=True, help_text='En caso de ser Chilen', max_length=16, null=True)),
                ('nacionalidad', models.CharField(max_length=16)),
                ('direccion', models.CharField(max_length=64, verbose_name='Direcci\xf3n')),
                ('club', models.CharField(blank=True, max_length=32, null=True, verbose_name='Club')),
                ('talla_polera', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='M', max_length=2, verbose_name='Talla de Polera')),
                ('medio_pago', models.CharField(choices=[('TRANSF', 'Transferencia')], default='TRANSFERENCIA', max_length=8, verbose_name='Medio de Pago')),
                ('edad_y_precio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoria_persona', to='inscripcion.CategoriaACompetir')),
            ],
            options={
                'verbose_name': 'Persona Inscrita',
                'verbose_name_plural': 'Listado Personas Inscritas',
            },
        ),
    ]
