# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0005_auto_20170215_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaacompetir',
            name='precio',
            field=models.CharField(max_length=12),
        ),
    ]
