# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-04 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0009_auto_20170215_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='anno',
            field=models.IntegerField(default=2017),
        ),
    ]
