# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-04 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0010_persona_anno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='rut',
            field=models.CharField(blank=True, help_text='12345678-5', max_length=15, null=True, verbose_name='RUT'),
        ),
    ]
