# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-04 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0011_auto_20170804_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='rut',
            field=models.CharField(default='aaaaa', help_text='12345678-5', max_length=15, unique=True, verbose_name='RUT'),
            preserve_default=False,
        ),
    ]
