# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-04 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0013_auto_20170804_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='anno',
            field=models.PositiveSmallIntegerField(blank=True, default=2017, null=True),
        ),
    ]
