# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('sub_titulo', models.CharField(max_length=32)),
                ('tipo', models.CharField(choices=[('HOTEL', 'Hotel'), ('CABA\xd1A', 'Caba\xf1a'), ('RESTORANT', 'Restorant'), ('OTROS', 'Otros')], default='CABA\xd1A', max_length=10)),
                ('estrellas', models.SmallIntegerField(blank=True, null=True)),
                ('pagina_web', models.URLField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='hoteles')),
                ('comuna', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.CharField(blank=True, max_length=64, null=True)),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('url_reservas', models.URLField()),
                ('mapa_google', models.URLField()),
            ],
            options={
                'verbose_name': 'Alojamiento',
                'verbose_name_plural': 'Alojamientos',
            },
        ),
    ]
