# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0002_auto_20161127_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='dato',
            name='mapa_google',
            field=models.URLField(default='google.cl'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dato',
            name='sub_titulo',
            field=models.CharField(default='Hola', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dato',
            name='url_reservas',
            field=models.URLField(default='google.cl'),
            preserve_default=False,
        ),
    ]
