# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 05:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0002_auto_20161214_2136'),
        ('hoteles', '0003_auto_20161129_1512'),
    ]

    operations = [
    ]
