# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Osorno, Valdivia, R\xedo Bueno, etc.', max_length=50, verbose_name='Nombre de la Comuna')),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Comuna de Chile',
                'verbose_name_plural': 'Comunas de Chile',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='los r\xedos', max_length=50, verbose_name='Nombre de la Regi\xf3n')),
                ('codigo', models.CharField(help_text='XVI, RM, etc..', max_length=7)),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Regi\xf3n de Chile',
                'verbose_name_plural': 'Regiones de Chile',
            },
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comuna_region', to='mapachile.Region'),
        ),
    ]
